### ISSUE TITLE
Use of Biderctional LSTM

### ISSUE THREAD

**Issue by tRosenflanz** [mp2893/retain#3]
Hi Edward,

This is more of a question than an actual issue so I will close it immediately: 

What do you think about the use of Bidirectional LSTM instead of just the reversed order? Do you think it impedes the interpretable spirit of the RETAIN or is it fine to use as long as it provides the boost in performance? I've been using concatenated Bidirectional lstm with moderate increase in AUC - I think due to concatenation of the outputs it is totally plausible that the network will select the order that provides more value but I am not entirely sure that this makes sense from clinical perspective. 

Do you have any thoughts on this?

Thanks,
Tim

**Comment by mp2893** [comment]
Hi Tim,

I would say that's an excellent idea.
The reason I used reverse time order was twofold: 
1) To encourage the model to consider recent visits more. 
2) To avoid the model from generating the same visit-level attention weights as it sees more visits.
But bi-directional LSTM, as you suggested, would be able to choose whatever makes sense (recent visit matters VS old visit matters). 
I should actually modify the code so that the RETAIN supports bi-directional LSTM (can't promise when I'll do it though).

Thanks,
Ed
